// Generated by CoffeeScript 1.7.0
(function() {
  $(document).ready(function(e) {
    var arrow, downArrow, height, snap, snap2, width;
    snap = Snap('.show-video-button');
    width = parseInt(snap.attr('width'));
    height = parseInt(snap.attr('height'));
    arrow = function(snap, width, height, arrowWidth) {
      var halfPoint;
      if (arrowWidth == null) {
        arrowWidth = 5;
      }
      halfPoint = width / 2;
      return snap.polyline(0, 0, halfPoint, height, width, 0, halfPoint, height - arrowWidth, 0, 0);
    };
    arrow(snap, width, height);
    snap2 = Snap(".hide-video-button");
    downArrow = arrow(snap2, width, height);
    return $(downArrow.node).css({
      transform: 'rotate(180deg)',
      'transform-origin': 'center'
    });
  });

}).call(this);
