// Generated by CoffeeScript 1.7.0
(function() {
  $(document).ready(function() {
    var $footer, SLIDE_DOWN_THRESHOLD, distanceMoved, fingerY, log, moveDown, pastDragThreshold, resetBottomPage, resetDragValues, showTopPage;
    SLIDE_DOWN_THRESHOLD = window.screen.height / 10;
    log = function(msg) {
      return console.log(msg);
    };
    $(document).foundation();
    $footer = $('.footer-container');
    $('.show-video-button, .hide-video-button').on('click', function() {
      $('.front-page-container').toggleClass('active');
      return $footer.toggleClass('active');
    });
    fingerY = null;
    distanceMoved = 0;
    moveDown = function(distance) {
      $footer.css('top', "+" + distance + "px");
      return distanceMoved += distance;
    };
    showTopPage = function() {
      $('.hide-video-button').trigger('click');
      $footer.removeAttr('style');
      setTimeout(function() {
        return $footer.removeAttr('style');
      }, 250);
      return resetDragValues();
    };
    resetBottomPage = function() {
      $footer.removeAttr('style');
      return resetDragValues();
    };
    pastDragThreshold = function() {
      return distanceMoved > SLIDE_DOWN_THRESHOLD;
    };
    Hammer($footer[0]).on('swipedown', function(e) {
      return showTopPage();
    });
    $('.logo').on('click', showTopPage);
    return resetDragValues = function() {
      var mouseY;
      fingerY = null;
      distanceMoved = 0;
      return mouseY = 0;
    };
  });

}).call(this);
