// Generated by CoffeeScript 1.7.0
(function() {
  $(document).ready(function(e) {
    var fillWithSVG, quotesAnimation;
    quotesAnimation = (localStorage || {}).quotesAnimation || "fadeInUp";
    $(".main-quote [class*=line]").each(function(index, elem) {
      setTimeout((function() {
        $(elem).addClass(quotesAnimation + " animated");
      }), index * 250);
    });
    fillWithSVG = function(element) {
      var $elem, snap;
      $elem = $(element);
      $elem.css("position", "relative");
      snap = new Snap($elem.width(), $elem.height());
      snap.attr({
        position: "absolute",
        top: 0,
        left: 0
      });
      $elem.append(snap.node);
      return snap;
    };
    $("a.red").each(function(index, elem) {
      var snap;
      snap = fillWithSVG(elem);
    });
  });

}).call(this);
